# -*- coding: utf-8 -*-
"""Python OOP Blackjack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItTRbIEhCEKaNpj2jJKEW2FdaqHyMoBa
"""

import random
import Hand
import Deck

class Dealer(Hand,Deck):

  def __init__(self,Hand):
    self.hand = Hand.get_hand()

  def new_card(self):
    self.hand.append(Deck.get_card(self))
    Deck.remove_card(self)

  def start_game(self):
    print(self.hand[0])