# -*- coding: utf-8 -*-
"""Python OOP Blackjack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItTRbIEhCEKaNpj2jJKEW2FdaqHyMoBa
"""

import random
import Deck

class Hand(Deck):

  def __init__(self,Deck):
    self.hand = Deck.starting_hand()

  def get_hand(self):
    return list(self.hand)