# -*- coding: utf-8 -*-
"""Python OOP Blackjack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItTRbIEhCEKaNpj2jJKEW2FdaqHyMoBa
"""

import random
from Deck import Deck

class Hand(Deck):

  def __init__(self,Deck):
    self.hand = Deck.starting_hand()
    if not isinstance(self.hand,list):
        raise TypeError("Hand is not legit")

  def get_hand(self):
    return list(self.hand)