# -*- coding: utf-8 -*-
"""Python OOP Blackjack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItTRbIEhCEKaNpj2jJKEW2FdaqHyMoBa
"""

import random
from Dealer import Dealer
from Deck import Deck
from Hand import Hand
from Player import Player

def main():
    print("To be filled")
    
    d = Deck()
    hp = Hand(d)
    hd = Hand(d)
    p = Player(hp)
    dea = Dealer(hd)
    
if __name__ == "__main__":
    main()