# -*- coding: utf-8 -*-
"""Python OOP Blackjack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItTRbIEhCEKaNpj2jJKEW2FdaqHyMoBa
"""

import random
import Hand
import Deck

class Player(Hand,Deck):

  balance = 500

  def __init__(self,Hand):
    self.hand = Hand.get_hand()

  def ask_bet(self):
    self.value_subt = input('Type bet: ')
    return int(self.value_subt)

  def subtract_balance(self):
    self.balance -= self.ask_bet()

  def check_balance(self):
    if self.ask_bet() > self.balance : True

  def win_game(self):
    self.balance += self.value_subt*2

  def new_card(self):
    self.Deck.get_card().append(self.hand)
    self.Deck.remove_card()

  def start_game(self):
    print(self.hand)

  def get_balance(self):
    return self.balance