# -*- coding: utf-8 -*-
"""Python OOP Blackjack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItTRbIEhCEKaNpj2jJKEW2FdaqHyMoBa
"""

import random

class Deck:

  deck = []
  colors = ['Hearts', 'Diamonds', 'Spades', 'Clubs']
  values = ['Ace','2','3','4','5','6','7','8','9','10','Queen','King','Jack']

  def __init__(self):
    self.value = self.values
    self.color = self.colors

    for i in self.values:
      for j in self.colors:
        self.deck.append(str(i +" of "+j))
    random.shuffle(self.deck)

  def remove_card(self):
    self.deck.pop(0)

  def show(self):
    print(self.deck)

  def get_deck(self):
    return self.deck

  def get_card(self):
    return self.deck[0]
  
  def starting_hand(self):
    return list(self.deck[0:2])

class Hand(Deck):

  def __init__(self,Deck):
    self.hand = Deck.starting_hand()

  def get_hand(self):
    return list(self.hand)

class Player(Hand,Deck):

  balance = 500

  def __init__(self,Hand):
    self.hand = Hand.get_hand()

  def ask_bet(self):
    self.value_subt = input('Type bet: ')
    return int(self.value_subt)

  def subtract_balance(self):
    self.balance -= self.ask_bet()

  def check_balance(self):
    if self.ask_bet() > self.balance : True

  def win_game(self):
    self.balance += self.value_subt*2

  def new_card(self):
    self.Deck.get_card().append(self.hand)
    self.Deck.remove_card()

  def start_game(self):
    print(self.hand)

  def get_balance(self):
    return self.balance

class Dealer(Hand,Deck):

  def __init__(self,Hand):
    self.hand = Hand.get_hand()

  def new_card(self):
    self.hand.append(Deck.get_card(self))
    Deck.remove_card(self)

  def start_game(self):
    print(self.hand[0])